apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone-new
  labels:
    app: capstone-new
spec:
  selector:
    matchLabels:
      app: capstone-new
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: capstone-new
    spec:
      containers:
      - name: capstone-new
        image: dinu17/hello-world:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
